name: Update Contribution Snake

on:
  schedule:
    # every hour (you can adjust)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) pull down your code
      - uses: actions/checkout@v3

      # 2) generate ONLY the SVG version of the snake
      - name: Generate contribution-snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          # your GitHub username (taken from repo owner)
          github_user_name: ${{ github.repository_owner }}
          # where to write the output file
          outputs: |
            output/github-contribution-grid-snake.svg

      # 3) commit & push if it changed
      - name: Commit and push updated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          if ! git diff --quiet; then
            git commit -m "chore: update contribution snake"
            git push
          else
            echo "No changes to commit"
          fi
