name: Update Contribution Snake

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create output directory
        run: mkdir -p output

      - name: Generate contribution snake SVG
        run: |
          npm install --no-save github-contribution-grid-snake
          npx github-contribution-grid-snake \
            --username ${{ github.repository_owner }} \
            --output ./output/github-contribution-grid-snake.svg

      - name: Commit and push updated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          if ! git diff --quiet; then
            git commit -m "chore: update contribution snake"
            git push
          else
            echo "No changes to commit"
          fi
